# Generated by Django 2.2 on 2021-07-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_itemlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
